# coding: utf-8

"""
    Checkbook API

    The Checkbook API enables businesses to programmatically send and receive payments using digital checks and other payment methods. With Checkbook, you can automate payment workflows, disburse funds instantly, and manage transactions securely—all without the delays and costs of traditional paper checks.

    The version of the OpenAPI document: 3.0.0
    Contact: support@checkbook.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from checkbook.models.create_digital_check_request_attachment import CreateDigitalCheckRequestAttachment
from checkbook.models.create_direct_check_request_number import CreateDirectCheckRequestNumber
from checkbook.models.multi_recipient import MultiRecipient
from checkbook.models.remittance_advice import RemittanceAdvice
from typing import Optional, Set
from typing_extensions import Self

class CreateMultiCheckRequest(BaseModel):
    """
    CreateMultiCheckRequest
    """ # noqa: E501
    account: Optional[StrictStr] = Field(default=None, description="Debit account id for funds (if sender has multiple bank accounts)")
    amount: Union[Annotated[float, Field(strict=True, ge=0.01)], Annotated[int, Field(strict=True, ge=1)]] = Field(description="Payment amount")
    attachment: Optional[CreateDigitalCheckRequestAttachment] = None
    comment: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="Comment field for payment")
    deposit_options: Optional[List[StrictStr]] = None
    description: Optional[StrictStr] = Field(default=None, description="Optional description/memo for payment")
    number: Optional[CreateDirectCheckRequestNumber] = None
    recipients: Annotated[List[MultiRecipient], Field(min_length=2, max_length=5)] = Field(description="Recipients")
    remittance_advice: Optional[Annotated[List[RemittanceAdvice], Field(min_length=1, max_length=50)]] = Field(default=None, description="List of the remittance records")
    __properties: ClassVar[List[str]] = ["account", "amount", "attachment", "comment", "deposit_options", "description", "number", "recipients", "remittance_advice"]

    @field_validator('deposit_options')
    def deposit_options_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['PRINT', 'MAIL', 'BANK', 'CARD', 'VCC', 'RTP', 'PAYPAL', 'WALLET', 'VENMO', 'INTERAC', 'WIRE']):
                raise ValueError("each list item must be one of ('PRINT', 'MAIL', 'BANK', 'CARD', 'VCC', 'RTP', 'PAYPAL', 'WALLET', 'VENMO', 'INTERAC', 'WIRE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateMultiCheckRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of attachment
        if self.attachment:
            _dict['attachment'] = self.attachment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of number
        if self.number:
            _dict['number'] = self.number.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in recipients (list)
        _items = []
        if self.recipients:
            for _item_recipients in self.recipients:
                if _item_recipients:
                    _items.append(_item_recipients.to_dict())
            _dict['recipients'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in remittance_advice (list)
        _items = []
        if self.remittance_advice:
            for _item_remittance_advice in self.remittance_advice:
                if _item_remittance_advice:
                    _items.append(_item_remittance_advice.to_dict())
            _dict['remittance_advice'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateMultiCheckRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account": obj.get("account"),
            "amount": obj.get("amount"),
            "attachment": CreateDigitalCheckRequestAttachment.from_dict(obj["attachment"]) if obj.get("attachment") is not None else None,
            "comment": obj.get("comment"),
            "deposit_options": obj.get("deposit_options"),
            "description": obj.get("description"),
            "number": CreateDirectCheckRequestNumber.from_dict(obj["number"]) if obj.get("number") is not None else None,
            "recipients": [MultiRecipient.from_dict(_item) for _item in obj["recipients"]] if obj.get("recipients") is not None else None,
            "remittance_advice": [RemittanceAdvice.from_dict(_item) for _item in obj["remittance_advice"]] if obj.get("remittance_advice") is not None else None
        })
        return _obj


