# coding: utf-8

"""
    Checkbook API

    The Checkbook API enables businesses to programmatically send and receive payments using digital checks and other payment methods. With Checkbook, you can automate payment workflows, disburse funds instantly, and manage transactions securely—all without the delays and costs of traditional paper checks.

    The version of the OpenAPI document: 3.0.0
    Contact: support@checkbook.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from checkbook.models.create_check_subscription_request_recipient import CreateCheckSubscriptionRequestRecipient
from checkbook.models.remittance_advice import RemittanceAdvice
from typing import Optional, Set
from typing_extensions import Self

class CreateCheckSubscriptionRequest(BaseModel):
    """
    CreateCheckSubscriptionRequest
    """ # noqa: E501
    account: Optional[StrictStr] = Field(default=None, description="Debit account id for funds (if sender has multiple bank accounts)")
    amount: Union[Annotated[float, Field(strict=True, ge=0.01)], Annotated[int, Field(strict=True, ge=1)]] = Field(description="Invoice amount")
    description: Optional[StrictStr] = Field(default=None, description="Description for check")
    duration: Optional[Annotated[int, Field(le=52, strict=True, ge=1)]] = Field(default=None, description="Optional number of times the subscription should recur (defaults to indefinite)")
    interval: StrictStr = Field(description="How often the subscription will recur")
    name: Annotated[str, Field(min_length=2, strict=True, max_length=180)] = Field(description="Name of recipient")
    recipient: CreateCheckSubscriptionRequestRecipient
    remittance_advice: Optional[Annotated[List[RemittanceAdvice], Field(min_length=1, max_length=50)]] = Field(default=None, description="List of the remittance records")
    start_date: Optional[date] = Field(default=None, description="Start date for subscription (this is the first date the subscription will be sent out and defaults to the current timestamp)")
    __properties: ClassVar[List[str]] = ["account", "amount", "description", "duration", "interval", "name", "recipient", "remittance_advice", "start_date"]

    @field_validator('interval')
    def interval_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['WEEKLY', 'MONTHLY']):
            raise ValueError("must be one of enum values ('WEEKLY', 'MONTHLY')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateCheckSubscriptionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of recipient
        if self.recipient:
            _dict['recipient'] = self.recipient.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in remittance_advice (list)
        _items = []
        if self.remittance_advice:
            for _item_remittance_advice in self.remittance_advice:
                if _item_remittance_advice:
                    _items.append(_item_remittance_advice.to_dict())
            _dict['remittance_advice'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if duration (nullable) is None
        # and model_fields_set contains the field
        if self.duration is None and "duration" in self.model_fields_set:
            _dict['duration'] = None

        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['start_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateCheckSubscriptionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account": obj.get("account"),
            "amount": obj.get("amount"),
            "description": obj.get("description"),
            "duration": obj.get("duration"),
            "interval": obj.get("interval"),
            "name": obj.get("name"),
            "recipient": CreateCheckSubscriptionRequestRecipient.from_dict(obj["recipient"]) if obj.get("recipient") is not None else None,
            "remittance_advice": [RemittanceAdvice.from_dict(_item) for _item in obj["remittance_advice"]] if obj.get("remittance_advice") is not None else None,
            "start_date": obj.get("start_date")
        })
        return _obj


