# coding: utf-8

"""
    Checkbook API

    The Checkbook API enables businesses to programmatically send and receive payments using digital checks and other payment methods. With Checkbook, you can automate payment workflows, disburse funds instantly, and manage transactions securely—all without the delays and costs of traditional paper checks.

    The version of the OpenAPI document: 3.0.0
    Contact: support@checkbook.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from checkbook.models.create_digital_check_request_attachment import CreateDigitalCheckRequestAttachment
from checkbook.models.create_physical_check_request_number import CreatePhysicalCheckRequestNumber
from checkbook.models.create_physical_check_request_remittance_advice import CreatePhysicalCheckRequestRemittanceAdvice
from checkbook.models.physical_check_recipient import PhysicalCheckRecipient
from typing import Optional, Set
from typing_extensions import Self

class CreatePhysicalCheckRequest(BaseModel):
    """
    CreatePhysicalCheckRequest
    """ # noqa: E501
    account: Optional[StrictStr] = Field(default=None, description="Debit account id for funds (if sender has multiple bank accounts)")
    amount: Union[Annotated[float, Field(strict=True, ge=0.01)], Annotated[int, Field(strict=True, ge=1)]] = Field(description="Payment amount")
    attachment: Optional[CreateDigitalCheckRequestAttachment] = None
    comment: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="Comment field for payment")
    description: Optional[StrictStr] = Field(default=None, description="Optional description/memo for payment")
    mail_type: Optional[StrictStr] = Field(default=None, description="Delivery options")
    name: Annotated[str, Field(min_length=2, strict=True, max_length=180)] = Field(description="Name of recipient")
    number: Optional[CreatePhysicalCheckRequestNumber] = None
    recipient: PhysicalCheckRecipient
    remittance_advice: Optional[CreatePhysicalCheckRequestRemittanceAdvice] = None
    __properties: ClassVar[List[str]] = ["account", "amount", "attachment", "comment", "description", "mail_type", "name", "number", "recipient", "remittance_advice"]

    @field_validator('mail_type')
    def mail_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['USPS_FIRST_CLASS', 'OVERNIGHT', 'TWO_DAY', 'USPS_CERTIFIED']):
            raise ValueError("must be one of enum values ('USPS_FIRST_CLASS', 'OVERNIGHT', 'TWO_DAY', 'USPS_CERTIFIED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatePhysicalCheckRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of attachment
        if self.attachment:
            _dict['attachment'] = self.attachment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of number
        if self.number:
            _dict['number'] = self.number.to_dict()
        # override the default output from pydantic by calling `to_dict()` of recipient
        if self.recipient:
            _dict['recipient'] = self.recipient.to_dict()
        # override the default output from pydantic by calling `to_dict()` of remittance_advice
        if self.remittance_advice:
            _dict['remittance_advice'] = self.remittance_advice.to_dict()
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatePhysicalCheckRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account": obj.get("account"),
            "amount": obj.get("amount"),
            "attachment": CreateDigitalCheckRequestAttachment.from_dict(obj["attachment"]) if obj.get("attachment") is not None else None,
            "comment": obj.get("comment"),
            "description": obj.get("description"),
            "mail_type": obj.get("mail_type"),
            "name": obj.get("name"),
            "number": CreatePhysicalCheckRequestNumber.from_dict(obj["number"]) if obj.get("number") is not None else None,
            "recipient": PhysicalCheckRecipient.from_dict(obj["recipient"]) if obj.get("recipient") is not None else None,
            "remittance_advice": CreatePhysicalCheckRequestRemittanceAdvice.from_dict(obj["remittance_advice"]) if obj.get("remittance_advice") is not None else None
        })
        return _obj


