# coding: utf-8

"""
    Checkbook API

    The Checkbook API enables businesses to programmatically send and receive payments using digital checks and other payment methods. With Checkbook, you can automate payment workflows, disburse funds instantly, and manage transactions securely—all without the delays and costs of traditional paper checks.

    The version of the OpenAPI document: 3.0.0
    Contact: support@checkbook.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from checkbook.models.create_digital_check_request_attachment import CreateDigitalCheckRequestAttachment
from checkbook.models.create_direct_check_request_number import CreateDirectCheckRequestNumber
from checkbook.models.remittance_advice import RemittanceAdvice
from typing import Optional, Set
from typing_extensions import Self

class CreateInstantCheckRequest(BaseModel):
    """
    CreateInstantCheckRequest
    """ # noqa: E501
    account: Optional[StrictStr] = Field(default=None, description="Debit account id for funds (if sender has multiple bank accounts)")
    amount: Union[Annotated[float, Field(strict=True, ge=0.01)], Annotated[int, Field(strict=True, ge=1)]] = Field(description="Payment amount")
    attachment: Optional[CreateDigitalCheckRequestAttachment] = None
    card_number: StrictStr = Field(description="Card number")
    comment: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="Comment field for payment")
    description: Optional[StrictStr] = Field(default=None, description="Optional description/memo for payment")
    expiration_date: StrictStr = Field(description="Card expiration date")
    name: Annotated[str, Field(min_length=2, strict=True, max_length=180)] = Field(description="Name of recipient")
    number: Optional[CreateDirectCheckRequestNumber] = None
    recipient: Annotated[str, Field(strict=True, max_length=80)] = Field(description="Email or text enabled phone number/id of recipient")
    remittance_advice: Optional[Annotated[List[RemittanceAdvice], Field(min_length=1, max_length=50)]] = Field(default=None, description="List of the remittance records")
    __properties: ClassVar[List[str]] = ["account", "amount", "attachment", "card_number", "comment", "description", "expiration_date", "name", "number", "recipient", "remittance_advice"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateInstantCheckRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of attachment
        if self.attachment:
            _dict['attachment'] = self.attachment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of number
        if self.number:
            _dict['number'] = self.number.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in remittance_advice (list)
        _items = []
        if self.remittance_advice:
            for _item_remittance_advice in self.remittance_advice:
                if _item_remittance_advice:
                    _items.append(_item_remittance_advice.to_dict())
            _dict['remittance_advice'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateInstantCheckRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account": obj.get("account"),
            "amount": obj.get("amount"),
            "attachment": CreateDigitalCheckRequestAttachment.from_dict(obj["attachment"]) if obj.get("attachment") is not None else None,
            "card_number": obj.get("card_number"),
            "comment": obj.get("comment"),
            "description": obj.get("description"),
            "expiration_date": obj.get("expiration_date"),
            "name": obj.get("name"),
            "number": CreateDirectCheckRequestNumber.from_dict(obj["number"]) if obj.get("number") is not None else None,
            "recipient": obj.get("recipient"),
            "remittance_advice": [RemittanceAdvice.from_dict(_item) for _item in obj["remittance_advice"]] if obj.get("remittance_advice") is not None else None
        })
        return _obj


