# coding: utf-8

"""
    Checkbook API

    The Checkbook API enables businesses to programmatically send and receive payments using digital checks and other payment methods. With Checkbook, you can automate payment workflows, disburse funds instantly, and manage transactions securely—all without the delays and costs of traditional paper checks.

    The version of the OpenAPI document: 3.0.0
    Contact: support@checkbook.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from checkbook.models.create_subscription_response_recipient import CreateSubscriptionResponseRecipient
from typing import Optional, Set
from typing_extensions import Self

class CreateSubscriptionResponse(BaseModel):
    """
    CreateSubscriptionResponse
    """ # noqa: E501
    account: Optional[StrictStr] = Field(default=None, description="Debit/credit account id for funds")
    amount: Union[StrictFloat, StrictInt] = Field(description="Subscription amount")
    var_date: StrictStr = Field(description="Subscription creation timestamp", alias="date")
    description: Optional[StrictStr] = Field(description="Subscription description")
    duration: Optional[StrictInt] = Field(default=None, description="Number of times the subscription will recur (null indicates indefinite)")
    id: StrictStr = Field(description="Unique identifier for subscription")
    interval: StrictStr = Field(description="How often the subscription will recur")
    name: Optional[StrictStr] = Field(default=None, description="Name of third party who is receiving the check/invoice")
    recipient: Optional[CreateSubscriptionResponseRecipient] = None
    start_date: StrictStr = Field(description="Subscription start date")
    type: StrictStr = Field(description="Type of the subscription")
    __properties: ClassVar[List[str]] = ["account", "amount", "date", "description", "duration", "id", "interval", "name", "recipient", "start_date", "type"]

    @field_validator('interval')
    def interval_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['WEEKLY', 'MONTHLY']):
            raise ValueError("must be one of enum values ('WEEKLY', 'MONTHLY')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['INVOICE', 'CHECK']):
            raise ValueError("must be one of enum values ('INVOICE', 'CHECK')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateSubscriptionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of recipient
        if self.recipient:
            _dict['recipient'] = self.recipient.to_dict()
        # set to None if account (nullable) is None
        # and model_fields_set contains the field
        if self.account is None and "account" in self.model_fields_set:
            _dict['account'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if duration (nullable) is None
        # and model_fields_set contains the field
        if self.duration is None and "duration" in self.model_fields_set:
            _dict['duration'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateSubscriptionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account": obj.get("account"),
            "amount": obj.get("amount"),
            "date": obj.get("date"),
            "description": obj.get("description"),
            "duration": obj.get("duration"),
            "id": obj.get("id"),
            "interval": obj.get("interval"),
            "name": obj.get("name"),
            "recipient": CreateSubscriptionResponseRecipient.from_dict(obj["recipient"]) if obj.get("recipient") is not None else None,
            "start_date": obj.get("start_date"),
            "type": obj.get("type")
        })
        return _obj


