# coding: utf-8

"""
    Checkbook API

    The Checkbook API enables businesses to programmatically send and receive payments using digital checks and other payment methods. With Checkbook, you can automate payment workflows, disburse funds instantly, and manage transactions securely—all without the delays and costs of traditional paper checks.

    The version of the OpenAPI document: 3.0.0
    Contact: support@checkbook.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class GetInvoiceResponse(BaseModel):
    """
    GetInvoiceResponse
    """ # noqa: E501
    amount: Union[StrictFloat, StrictInt] = Field(description="Invoice amount")
    attachment_uri: Optional[StrictStr] = Field(default=None, description="URI for invoice attachment")
    check_id: Optional[StrictStr] = Field(default=None, description="Associated check number")
    var_date: StrictStr = Field(description="Invoice creation timestamp", alias="date")
    description: StrictStr = Field(description="Invoice description")
    direction: StrictStr = Field(description="Direction")
    id: StrictStr = Field(description="Unique identifier for invoice")
    name: Optional[StrictStr] = Field(default=None, description="Name of third party who sent/received the invoice")
    number: StrictStr = Field(description="Invoice number")
    recipient: Optional[StrictStr] = Field(default=None, description="Email/id of the invoice recipient")
    status: StrictStr = Field(description="Current status of the invoice")
    __properties: ClassVar[List[str]] = ["amount", "attachment_uri", "check_id", "date", "description", "direction", "id", "name", "number", "recipient", "status"]

    @field_validator('direction')
    def direction_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['INCOMING', 'OUTGOING']):
            raise ValueError("must be one of enum values ('INCOMING', 'OUTGOING')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetInvoiceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if attachment_uri (nullable) is None
        # and model_fields_set contains the field
        if self.attachment_uri is None and "attachment_uri" in self.model_fields_set:
            _dict['attachment_uri'] = None

        # set to None if check_id (nullable) is None
        # and model_fields_set contains the field
        if self.check_id is None and "check_id" in self.model_fields_set:
            _dict['check_id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if recipient (nullable) is None
        # and model_fields_set contains the field
        if self.recipient is None and "recipient" in self.model_fields_set:
            _dict['recipient'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetInvoiceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "attachment_uri": obj.get("attachment_uri"),
            "check_id": obj.get("check_id"),
            "date": obj.get("date"),
            "description": obj.get("description"),
            "direction": obj.get("direction"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "number": obj.get("number"),
            "recipient": obj.get("recipient"),
            "status": obj.get("status")
        })
        return _obj


