# coding: utf-8

"""
    Checkbook API

    The Checkbook API enables businesses to programmatically send and receive payments using digital checks and other payment methods. With Checkbook, you can automate payment workflows, disburse funds instantly, and manage transactions securely—all without the delays and costs of traditional paper checks.

    The version of the OpenAPI document: 3.0.0
    Contact: support@checkbook.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from checkbook.models.merchant_response_address import MerchantResponseAddress
from typing import Optional, Set
from typing_extensions import Self

class MerchantResponse(BaseModel):
    """
    Merchant field
    """ # noqa: E501
    address: Optional[MerchantResponseAddress] = None
    incorporation_date: Optional[StrictStr] = Field(default=None, description="Business incorporation or formation date")
    industry: Optional[StrictStr] = Field(default=None, description="Industry sector")
    legal_firstname: Optional[StrictStr] = Field(default=None, description="Principal officer first name")
    legal_lastname: Optional[StrictStr] = Field(default=None, description="Principal officer last name")
    principal_address: Optional[MerchantResponseAddress] = None
    principal_citizenship_status: Optional[StrictStr] = Field(default=None, description="One of a standard set of values that indicate the citizenship status")
    principal_occupation: Optional[StrictStr] = Field(default=None, description="One of a standard set of values that indicate customer occupation")
    tax_id: Optional[StrictStr] = Field(default=None, description="Tax ID")
    website: Optional[StrictStr] = Field(default=None, description="Company website")
    __properties: ClassVar[List[str]] = ["address", "incorporation_date", "industry", "legal_firstname", "legal_lastname", "principal_address", "principal_citizenship_status", "principal_occupation", "tax_id", "website"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MerchantResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of principal_address
        if self.principal_address:
            _dict['principal_address'] = self.principal_address.to_dict()
        # set to None if incorporation_date (nullable) is None
        # and model_fields_set contains the field
        if self.incorporation_date is None and "incorporation_date" in self.model_fields_set:
            _dict['incorporation_date'] = None

        # set to None if industry (nullable) is None
        # and model_fields_set contains the field
        if self.industry is None and "industry" in self.model_fields_set:
            _dict['industry'] = None

        # set to None if legal_firstname (nullable) is None
        # and model_fields_set contains the field
        if self.legal_firstname is None and "legal_firstname" in self.model_fields_set:
            _dict['legal_firstname'] = None

        # set to None if legal_lastname (nullable) is None
        # and model_fields_set contains the field
        if self.legal_lastname is None and "legal_lastname" in self.model_fields_set:
            _dict['legal_lastname'] = None

        # set to None if principal_citizenship_status (nullable) is None
        # and model_fields_set contains the field
        if self.principal_citizenship_status is None and "principal_citizenship_status" in self.model_fields_set:
            _dict['principal_citizenship_status'] = None

        # set to None if principal_occupation (nullable) is None
        # and model_fields_set contains the field
        if self.principal_occupation is None and "principal_occupation" in self.model_fields_set:
            _dict['principal_occupation'] = None

        # set to None if tax_id (nullable) is None
        # and model_fields_set contains the field
        if self.tax_id is None and "tax_id" in self.model_fields_set:
            _dict['tax_id'] = None

        # set to None if website (nullable) is None
        # and model_fields_set contains the field
        if self.website is None and "website" in self.model_fields_set:
            _dict['website'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MerchantResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": MerchantResponseAddress.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "incorporation_date": obj.get("incorporation_date"),
            "industry": obj.get("industry"),
            "legal_firstname": obj.get("legal_firstname"),
            "legal_lastname": obj.get("legal_lastname"),
            "principal_address": MerchantResponseAddress.from_dict(obj["principal_address"]) if obj.get("principal_address") is not None else None,
            "principal_citizenship_status": obj.get("principal_citizenship_status"),
            "principal_occupation": obj.get("principal_occupation"),
            "tax_id": obj.get("tax_id"),
            "website": obj.get("website")
        })
        return _obj


