# coding: utf-8

"""
    Checkbook API

    The Checkbook API enables businesses to programmatically send and receive payments using digital checks and other payment methods. With Checkbook, you can automate payment workflows, disburse funds instantly, and manage transactions securely—all without the delays and costs of traditional paper checks.

    The version of the OpenAPI document: 3.0.0
    Contact: support@checkbook.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from checkbook.models.update_merchant_address import UpdateMerchantAddress
from checkbook.models.update_principal_address import UpdatePrincipalAddress
from typing import Optional, Set
from typing_extensions import Self

class Merchant(BaseModel):
    """
    Merchant fields
    """ # noqa: E501
    address: Optional[UpdateMerchantAddress] = None
    incorporation_date: Optional[date] = Field(default=None, description="Business incorporation or formation date")
    industry: Optional[StrictInt] = Field(default=None, description="Industry sector")
    legal_firstname: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="Principal officer first name")
    legal_lastname: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="Principal officer last name")
    principal_address: Optional[UpdatePrincipalAddress] = None
    principal_citizenship_status: Optional[StrictStr] = Field(default=None, description="One of a standard set of values that indicate the citizenship status")
    principal_occupation: Optional[Annotated[str, Field(strict=True, max_length=40)]] = Field(default=None, description="Occupation of principal")
    tax_id: Optional[Annotated[str, Field(min_length=9, strict=True, max_length=9)]] = Field(default=None, description="Tax ID")
    website: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="Company website")
    __properties: ClassVar[List[str]] = ["address", "incorporation_date", "industry", "legal_firstname", "legal_lastname", "principal_address", "principal_citizenship_status", "principal_occupation", "tax_id", "website"]

    @field_validator('industry')
    def industry_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([11, 21, 22, 23, 33, 42, 45, 49, 51, 52, 53, 54, 55, 56, 61, 62, 71, 72, 81, 92, 441, 519, 524, 624, 4541, 5411, 5614, 54112, 541211, 541214, 541614]):
            raise ValueError("must be one of enum values (11, 21, 22, 23, 33, 42, 45, 49, 51, 52, 53, 54, 55, 56, 61, 62, 71, 72, 81, 92, 441, 519, 524, 624, 4541, 5411, 5614, 54112, 541211, 541214, 541614)")
        return value

    @field_validator('principal_citizenship_status')
    def principal_citizenship_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['us_citizen', 'resident', 'non_resident']):
            raise ValueError("must be one of enum values ('us_citizen', 'resident', 'non_resident')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Merchant from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of principal_address
        if self.principal_address:
            _dict['principal_address'] = self.principal_address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Merchant from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": UpdateMerchantAddress.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "incorporation_date": obj.get("incorporation_date"),
            "industry": obj.get("industry"),
            "legal_firstname": obj.get("legal_firstname"),
            "legal_lastname": obj.get("legal_lastname"),
            "principal_address": UpdatePrincipalAddress.from_dict(obj["principal_address"]) if obj.get("principal_address") is not None else None,
            "principal_citizenship_status": obj.get("principal_citizenship_status"),
            "principal_occupation": obj.get("principal_occupation"),
            "tax_id": obj.get("tax_id"),
            "website": obj.get("website")
        })
        return _obj


