# coding: utf-8

"""
    Checkbook API

    The Checkbook API enables businesses to programmatically send and receive payments using digital checks and other payment methods. With Checkbook, you can automate payment workflows, disburse funds instantly, and manage transactions securely—all without the delays and costs of traditional paper checks.

    The version of the OpenAPI document: 3.0.0
    Contact: support@checkbook.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class RegisterUserRequest(BaseModel):
    """
    RegisterUserRequest
    """ # noqa: E501
    business_name: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=180)]] = Field(default=None, description="Business name of user")
    email: Annotated[str, Field(min_length=2, strict=True, max_length=180)] = Field(description="Email of user")
    first_name: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=180)]] = Field(default=None, description="First name of user")
    last_name: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=180)]] = Field(default=None, description="Last name of user")
    password: Annotated[str, Field(min_length=0, strict=True, max_length=180)] = Field(description="User password")
    referral_code: Optional[StrictStr] = Field(default=None, description="Referral code")
    __properties: ClassVar[List[str]] = ["business_name", "email", "first_name", "last_name", "password", "referral_code"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RegisterUserRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if referral_code (nullable) is None
        # and model_fields_set contains the field
        if self.referral_code is None and "referral_code" in self.model_fields_set:
            _dict['referral_code'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RegisterUserRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "business_name": obj.get("business_name"),
            "email": obj.get("email"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "password": obj.get("password"),
            "referral_code": obj.get("referral_code")
        })
        return _obj


