# coding: utf-8

"""
    Checkbook API

    The Checkbook API enables businesses to programmatically send and receive payments using digital checks and other payment methods. With Checkbook, you can automate payment workflows, disburse funds instantly, and manage transactions securely—all without the delays and costs of traditional paper checks.

    The version of the OpenAPI document: 3.0.0
    Contact: support@checkbook.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class UpdateDirectoryAddress(BaseModel):
    """
    UpdateDirectoryAddress
    """ # noqa: E501
    city: Optional[Annotated[str, Field(strict=True, max_length=40)]] = Field(default=None, description="City")
    country: Optional[StrictStr] = Field(default=None, description="Country")
    line_1: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="Line 1")
    line_2: Optional[StrictStr] = Field(default=None, description="Line 2")
    state: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(default=None, description="State")
    zip: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, description="Zip/postal code")
    __properties: ClassVar[List[str]] = ["city", "country", "line_1", "line_2", "state", "zip"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateDirectoryAddress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if line_2 (nullable) is None
        # and model_fields_set contains the field
        if self.line_2 is None and "line_2" in self.model_fields_set:
            _dict['line_2'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateDirectoryAddress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "city": obj.get("city"),
            "country": obj.get("country"),
            "line_1": obj.get("line_1"),
            "line_2": obj.get("line_2"),
            "state": obj.get("state"),
            "zip": obj.get("zip")
        })
        return _obj


